apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-backend-bar-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc
      version: bar
  template:
    metadata:
      labels:
        app: grpc
        version: bar
    spec:
      containers:
      - image: docker.io/ccieliu/mesh-demo
        imagePullPolicy: IfNotPresent
        name: mesh-demo
        ports:
        - containerPort: 50051
        env:
        - name: APP_VERSION
          value: grpc-bar-v1.0
        command: ['python3']
        args: ["/data/grpc-backend.py"]