apiVersion: v1
kind: Service
metadata:
  name: web-app-foo-svc
  labels:
    app: web-app-foo
    service: web-app-foo-svc
spec:
  ports:
  - name: web-app
    port: 8000
    targetPort: 5000
  selector:
    app: web-app
    version: foo
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-bar-svc
  labels:
    app: web-app-bar
    service: web-app-bar-svc
spec:
  ports:
  - name: web-app
    port: 8000
    targetPort: 5000
  selector:
    app: web-app
    version: bar